---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/10/2025 7:13 PM
---
---
DEBUG_MODE = false

handler = require("event_handler")
handler.add_lib(require("__advanced_target_priorities__/gui/gui_events"))

local RemoteApi = require("__advanced_target_priorities__/remote_api")
remote.add_interface("advanced_target_priorities", RemoteApi)