---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/10/2025 7:33 PM
---

local RemoteAPI = {}

---
--- Print global for debug purpose when you run remote.call("advanced_target_priorities", "print_global")"
---
function RemoteAPI.print_global()
    helpers.write_file("advanced_target_priorities/storage.json",helpers.table_to_json(util.copy(storage)))
end

return RemoteAPI