---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/13/2025 11:13 PM
---

local PresetWindow = {
    root_name = 'advanced_target_priority_preset'
}

function PresetWindow.show(player)
    PresetWindow.hide(player)

    local gui = player.gui.screen
    
    local container = gui.add{
        type = "frame",
        name = PresetWindow.root_name,
        direction="vertical",
    }
    container.style.vertically_stretchable = false
    container.style.width = 480
    container.style.height = 320

    local top_horizontal = container.add {
        type = "flow",
        direction="horizontal"
    }
    top_horizontal.add { type = "label", caption = { "gui-target-attachment.preset_window_title" } }
    local pusher = top_horizontal.add { type = "empty-widget", style = "draggable_space_header" }
    pusher.style.vertically_stretchable = true
    pusher.style.horizontally_stretchable = true
    pusher.drag_target = container

    local close_button = top_horizontal.add { type = "sprite-button",
                                          name = "erm_quality_points_detail_close_button",
                                          sprite = "utility/close",
                                          style = "frame_action_button",
                                          tooltip = { "gui.back-instruction" }
    }
    close_button.style.width = 24
    close_button.style.height = 24
    close_button.style.horizontal_align = "right"





    
    container.force_auto_center()
    container.bring_to_front()
end

function PresetWindow.hide(player)
    if player.gui.screen[PresetWindow.root_name] then
        player.gui.screen[PresetWindow.root_name].destroy()
    end
end

return PresetWindow